# Replace all project with project name
name: wp-project
recipe: wordpress
config:
  php: '7.4'
  composer_version: '2' # set to 1 | 1-latest | 2 | 2-latest https://docs.lando.dev/config/php.html#installing-composer
  via: apache # Nginx or apache
  webroot: .
  database: mysql # Mariadb or mysql
  xdebug: true
  config:
    # https://github.com/lando/lando/blob/master/plugins/lando-services/services/php/php.ini
    php: config/php.ini
    # Config/httpd.conf for apache or nginx.conf for nginx
    # https://github.com/lando/lando/blob/master/plugins/lando-services/services/nginx/nginx.conf
    server: config/nginx.conf
    # Comment out if using apache
    params: config/params
services:
  node:
    type: node
    globals:
      gulp-cli: latest
  mailhog:
    type: mailhog
    hogfrom:
      - appserver
  pma:
    type: phpmyadmin
    hosts:
      - database
tooling:
  npm:
    service: node
  node:
    service: node
  gulp:
    service: node
  yarn:
    service: node
  php:
    service: appserver
proxy:
  # Appserver_nginx or appserver for apache
  appserver:
    - wp-project.lndo.site
  mailhog:
    - mail.wp-project.lndo.site
  pma:
    - pma.wp-project.lndo.site